services:
  # arangodb:
  #   image: arangodb:3.7
  #   ports:
  #     - 8529:8529
  #   env_file: arangodb.env
  #   healthcheck:
  #     test: ["CMD", "wget", "--spider", "http://arangodb:8529/"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 10s
  gitocular:
    image: schoeberlt/gitocular:latest
    tty: true
    ports:
      - 48763:48763
      - 8080:8080
    env_file: binocular.env
    volumes:
      - ./:/output
    #command: ["https://github.com/schoeberlt/jsonrestaurants.git"]
    # depends_on:
    #   arangodb:
    #     condition: service_healthy
