name: "Docker env"
description: "Setting env variables for Docker builds"
inputs:
  imageName: 
    description: 'image name'
    default: 'No name provided'
runs:
  using: "composite"
  steps: 
    - shell: bash
      run: |
        # SHORT_SHA source: https://stackoverflow.com/questions/59810838/how-to-get-the-short-sha-for-the-github-workflow
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
        echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV
        echo "SHORT_SHA" ${SHORT_SHA}
        #
        IMAGE_NAME="${IMAGE_NAMESPACE}/binocular-frontend"
        echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
        echo "IMAGE_NAME" ${IMAGE_NAME}
        #
        IMAGE_TAG="${GITHUB_REF_NAME////_}-${SHORT_SHA}"
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
        echo "IMAGE_TAG" ${IMAGE_TAG}
    - id: nvmrc_node_version
      shell: bash
      run: |
        cat .nvmrc
        NODE_VERSION=$(cat .nvmrc | tr -cd '[:digit:].')
        echo "NODE_VERSION=${NODE_VERSION}" >> $GITHUB_OUTPUT
