env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - prettier
  - lambdas
parserOptions:
  ecmaVersion: 8
  sourceType: 'module'
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      printWidth: 140
  no-console: off
  max-len: ["error", { "code": 140 }]
  comma-dangle: ["error", "never"]
  operator-linebreak: ['error', 'after', { "overrides": { "?": "before", ":": "before"} }]
  quotes:
    - error
    - single
    - avoidEscape: true
plugins:
  - prettier
