image: node:8

services:
 - name: arangodb/arangodb:3.1.25
   alias: arango

before_script:
 - npm install

test:
  stage: test
  script:
    npm run coverage

lint:
  stage: test
  script:
    npm run check
