language: node_js
node_js:
  - "8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # See documentation https://www.npmjs.com/package/nodegit
    packages:
      - libstdc++-4.9-dev # See documentation https://www.npmjs.com/package/nodegit

cache:
  directories:
    - "node_modules"

jobs:
  include:
    # Run linting
    - stage: lint
      script: npm run eslint
    # Run tests
    - stage: test
      script: npm run test

stages:
  - lint
  - test
