version: "3.8"

services:
  db:
    image: ghcr.io/inso-tuwien/binocular-database:latest
    container_name: binocular_db
    restart: unless-stopped
    ports:
      - "8529:8529"

  binocular-init:
    image: ghcr.io/inso-tuwien/binocular-backend:latest
    depends_on:
      - db
    container_name: "binocular_init"
    tty: true
    environment:
      - DEBUG=idx*,importer*,git*,db*,context*
    command:
      [
        "tsx",
        "binocular.js",
        "--no-open",
        "--no-server",
        "/app/binocular/repo/test-repo"
      ]
    volumes:
      - type: bind
        source: .binocularrc
        target: /app/binocular/repo/test-repo/.binocularrc
        read_only: true
      - ./:/app/binocular/repo/test-repo

  binocular:
    container_name: binocular_app
    image: ghcr.io/inso-tuwien/binocular-frontend:latest
    ports:
      - 8088:80
