runs:
  using: "composite"
  steps:
    - name: Log in to the Container registry
      shell: bash
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Builder Buildx
      shell: bash
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      shell: bash
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: ${{ runner.os }}-buildx-
