name: "My Shared Steps"
description: "My Shared Steps"
inputs:
  imageName: 
    description: 'image name'
    default: 'No name provided'
runs:
  using: "composite"
  steps: 
    # - run: echo Hello ${{ inputs.imageName }}.
    #   shell: bash
    # - run: echo "Nice to meet you!"
    #   shell: pwsh
    - name: Set docker image env var
      shell: bash
      run: |
        # SHORT_SHA source: https://stackoverflow.com/questions/59810838/how-to-get-the-short-sha-for-the-github-workflow
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
        echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV
        echo "SHORT_SHA" ${SHORT_SHA}
        #
        IMAGE_NAME="${IMAGE_NAMESPACE}/binocular-frontend"
        echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
        echo "IMAGE_NAME" ${IMAGE_NAME}
        #
        IMAGE_TAG="${GITHUB_REF_NAME////_}-${SHORT_SHA}"
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
        echo "IMAGE_TAG" ${IMAGE_TAG}
