env:
  es6: true
  browser: true
extends:
  - eslint:recommended
  - prettier
parserOptions:
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      printWidth: 100
      jsxBracketSameLine: true
  no-console: off
  quotes:
    - error
    - single
    - avoidEscape: true
  react/jsx-uses-vars: 1
plugins:
  - prettier
  - react
