env:
  es6: true
  browser: true
extends:
  - eslint:recommended
  - prettier
  - lambdas
parserOptions:
  ecmaVersion: 8
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      printWidth: 140
      jsxBracketSameLine: true
  no-console: off
  max-len: ["error", { "code": 140 }]
  comma-dangle: ["error", "never"]
  operator-linebreak: ['error', 'after', { "overrides": { "?": "before", ":": "before"} }]
  quotes:
    - error
    - single
    - avoidEscape: true
  react/jsx-uses-vars: 1
  linebreak-style: ["error", "unix"]
plugins:
  - prettier
  - react
