name: Docker Image CI

on: push
# on:
#   push:
#     branches:
#       - develop
#       - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: "ghcr.io/inso-tuwien"

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setting env variables
        uses: ./.github/actions/docker-commons/
        with: 
          imageName: binocular-frontend

      - name: Echo docker tags
        run: |
          echo ${{ env.IMAGE_NAME }}:${{ env.IMAGE_NAME}}
          echo ${{ env.IMAGE_NAME }}:${GITHUB_RUN_ID}
          echo ${{ env.IMAGE_NAME }}:${{ github.run_id }}
          echo ${{ env.IMAGE_NAME }}:latest

      - name: Get NODE_VERSION from .nvmrc
        run: |
          cat .nvmrc
          NODE_VERSION=$(cat .nvmrc | tr -cd '[:digit:].')
          echo "NODE_VERSION=${NODE_VERSION}" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Builder Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: docker/Dockerfile.frontend
          push: true
          build-args: |
            NODE_VERSION=${{ env.NODE_VERSION }}
            NPM_BUILD_CMD=build:prod
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.BINOCULAR_FRONTEND_IMAGE_TAG}}
            ${{ env.IMAGE_NAME }}:${{ github.run_id }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
