name: Build Binocular

on:
  push:
    branches:
      - feature/159

env:
  IMAGE_BASE_NAME: ghcr.io/inso-tuwien/binocular-arangodb_3.11.3

jobs:

  build:

    runs-on: ubuntu-latest
    services:

      arangodb:
        # image: arangodb:3.11
        image: ghcr.io/inso-tuwien/binocular-database:arangodb_3.11.3-no_volumes
        options: --name "arangodb_svc"
        ports:  
          - 8529:8529
        env: 
          ARANGO_ROOT_PASSWORD: openSesame

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set .pupilrc variables
      uses: microsoft/variable-substitution@v1   
      with:
        files: .binocularrc_ci
      env:
        github.auth.token: ${{ secrets.GITHUB_TOKEN }}

    - name: Rename binocularrc
      run: mv .binocularrc_ci .binocularrc 

    - name: Set node version
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm

    # Source: https://www.voorhoede.nl/en/blog/super-fast-npm-install-on-github-actions/
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    - name: Install dependencies
      run: npm ci

    - name: Run binocular
      run: DEBUG=idx*,importer*,git*,db* node binocular.js --no-open --no-server

    - name: Build
      run: npm run build

    - name: Publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: binocular_ui
        path: dist/

    - name: docker ps
      run: docker ps
      
    - name: docker commit
      run: |
        echo ${IMAGE_BASE_NAME}:${GITHUB_RUN_ID}
        docker commit arangodb_svc ${IMAGE_BASE_NAME}:${GITHUB_RUN_ID}
      
    - name: docker images
      run: docker images

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push image
      run: |
        docker push ${IMAGE_BASE_NAME}:${GITHUB_RUN_ID}
        docker tag ${IMAGE_BASE_NAME}:${GITHUB_RUN_ID} ${IMAGE_BASE_NAME}:latest
        docker push ${IMAGE_BASE_NAME}:latest

    # - name: Run tests
    #   run: npm run test

    # - name: Collect coverage
    #   run: npm run coverage
