name: Build Database

on:
  push:
    branches:
      - "feature/159"

env:
  REGISTRY: ghcr.io
  ARANGO_VERSION: 3.11.3
  IMAGE_BASE_NAME: ghcr.io/inso-tuwien/binocular-arangodb_3.11.3
  ARANGO_IMAGE: ghcr.io/inso-tuwien/binocular-database:arangodb_3.11.3-no_volumes

jobs:
  build:
    runs-on: ubuntu-latest
    services:

      arangodb:
        # image: ghcr.io/inso-tuwien/binocular-database:develop-aa6ee159
        image: ${ARANGO_IMAGE}
        options: --name "arangodb_filled"
        ports:  
          - 8529:8529
        env: 
          # ARANGO_ROOT_PASSWORD: "openSesame"
          ARANGO_NO_AUTH: "1"

    steps:
    - name: Download ArangoClient
      run: wget -nv https://download.arangodb.com/arangodb311/Community/Linux/arangodb3-client-linux-3.11.1_x86_64.tar.gz -O arangodb3-client.tar.gz

    - name: Create client folder
      run: mkdir -p ./arangodb3-client

    - name: Extract ArangoClient
      run: tar -xf arangodb3-client.tar.gz -C ./arangodb3-client --strip-components=1
    
    - name: List contents
      run: ls -l ./arangodb3-client/bin

    - name: Download demo data
      run: wget https://raw.githubusercontent.com/arangodb/example-datasets/master/Bezirke/bezirke.csv
    
    - name: docker
      run: docker --version

    - name: docker ps
      run: docker ps
      
    - name: docker logs
      run: |
        docker logs arangodb_filled
        sleep 10
        docker logs arangodb_filled
            
    - name: Fill arangodb service db
      run: |
        pwd
        ls -l
        ./arangodb3-client/bin/arangoimport \
          --log.level "trace" \
          --collection "bezirke" \
          --create-collection true \
          --server.endpoint "http+tcp://127.0.0.1:8529" \
          --server.username "root" \
          --server.password "" \
          --server.database "GeoLiteCity" \
          --overwrite true \
          --progress true \
          --create-database true \
          --file bezirke.csv \
          --type=csv

    - name: Show databases
      run: |
          echo "db._databases();" | ./arangodb3-client/bin/arangosh \
            --log.level "trace" \
            --server.endpoint "http+tcp://127.0.0.1:8529" \
            --server.username "root" \
            --server.password ""
    
    - name: docker ps
      run: docker ps
      
    - name: docker commit
      run: |
        echo ${IMAGE_BASE_NAME}_${GITHUB_RUN_ID}
        docker commit arangodb_filled ${IMAGE_BASE_NAME}:${GITHUB_RUN_ID}
      
    - name: docker images
      run: docker images

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push image
      run: |
        docker push ${IMAGE_BASE_NAME}:${GITHUB_RUN_ID}
        docker tag ${IMAGE_BASE_NAME}:${GITHUB_RUN_ID} ${IMAGE_BASE_NAME}:latest
        docker push ${IMAGE_BASE_NAME}:latest
