name: Build Database

on:
  push:
    branches:
      - "feature/159"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ARANGO_IMAGE: ghcr.io/inso-tuwien/binocular-database:arangodb_3.11.3-no_volumes

jobs:
  build:
    runs-on: ubuntu-latest
    services:

      arangodb:
        # image: ghcr.io/inso-tuwien/binocular-database:develop-aa6ee159
        image: arangodb:3.11
        options: --name "arangodb"
        ports:  
          - 8529:8529
        env: 
          # ARANGO_ROOT_PASSWORD: "openSesame"
          ARANGO_NO_AUTH: "1"

    steps:
    - name: Download ArangoClient
      run: wget -nv https://download.arangodb.com/arangodb311/Community/Linux/arangodb3-client-linux-3.11.1_x86_64.tar.gz -O arangodb3-client.tar.gz

    - name: Create client folder
      run: mkdir -p ./arangodb3-client

    - name: Extract ArangoClient
      run: tar -xf arangodb3-client.tar.gz -C ./arangodb3-client --strip-components=1
    
    - name: List contents
      run: ls -l ./arangodb3-client/bin

    # - name: Download demo data
    #   run: wget https://raw.githubusercontent.com/arangodb/example-datasets/master/Bezirke/bezirke.csv
    
    - name: docker
      run: docker --version

    - name: docker ps
      run: docker ps
      
    - name: docker logs
      run: |
        docker logs arangodb
        sleep 5
        docker logs arangodb

    # - name: wait
    #   uses: nev7n/wait_for_response@v1
    #   with:
    #     url: 'http://127.0.0.1:8529/_api/version'
    #     responseCode: 200
    #     timeout: 2000
    #     interval: 1500
    #   # curl http://127.0.0.1:8529/_api/version
    # # - name: sleep
    # #   run: sleep 30

    - name: Show databases
      run: |
          echo "db._databases();" | ./arangodb3-client/bin/arangosh \
            --log.level "trace" \
            --server.ask-jwt-secret false \
            --server.endpoint "http+tcp://127.0.0.1:8529"
            # --server.username "root" \
            # --server.password ""
            
    # - name: Fill arangodb service db
    #   # working-directory: ./arangodb3-client/bin
    #   run: |
    #     pwd
    #     ls -l
    #     ./arangodb3-client/bin/arangoimport \
    #       --log.level "trace" \
    #       --collection "bezirke" \
    #       --create-collection true \
    #       --server.endpoint "http+tcp://arangodb:8529" \
    #       --server.username "root" \
    #       --server.password "" \
    #       --server.database "GeoLiteCity" \
    #       --overwrite true \
    #       --progress true \
    #       --create-database true \
    #       --file bezirke.csv \
    #       --type=csv
    
